apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dfl99j2av-java-springboot 
  janus-idp.io/tekton: dfl99j2av-java-springboot
  backstage.io/kubernetes-id: dfl99j2av-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dfl99j2av-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml